Choose supplier feature
Revature-DartCart/DartCart-Server pull request #24
Opened 2022-03-04 21:32 UTC by ramirez45

choose seller feature backend

2022-03-04 21:44 UTC, iatenine requested changes
Need some changes as specified in review + merge conflicts resolved between this branch and `dev` before merge

2022-03-04 21:44 UTC, iatenine commented on src/main/java/com/revature/configs/SecurityConfiguration.java
> +//        http.authorizeRequests()
Why is this being removed? Is it established elsewhere?

2022-03-04 21:44 UTC, iatenine commented on src/main/java/com/revature/controllers/SellerController.java
> +//    @GetMapping("/shop_products/{id}")
There are no routes available in this function. Should the file be removed completely?

2022-03-07 15:07 UTC, RichardSimpson235 commented on src/main/java/com/revature/models/ShopProduct.java
> +    private int shop_product_id;
Why was this changed?

2022-03-07 16:10 UTC, iatenine commented
Seems to be redundant due to a previous merge

2022-03-07 16:10 UTC, closed without merging